variables:

test:
  stage: test
  tags:
    - dalfcs_docker_autoscale
  image: maven:3.8.3-openjdk-17
  script: 
  - cd server
  - mvn clean install 
  - mvn test
  only:
    refs:
      - branches

build:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  image: maven:3.8.3-openjdk-17
  script:
    - cd server
    - mvn clean install 
    - mvn compile
  only:
    refs:
      - branches